/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Bart Kooijmans
 */
public class ConnectionGUI extends javax.swing.JPanel
{

    private Connection activeConnection;
    private Element startingElement;
    private MainController guiController;
    private JFileChooser linkFileChooser = new JFileChooser();

    /**
     * Creates new form ConnectionGUI
     */
    public ConnectionGUI(Element startElement, MainController modelGuiController)
    {
        guiController = modelGuiController;
        startingElement = startElement;
        activeConnection = new Connection();
        String ID = guiController.findNextAvailableConnectionID();
        activeConnection.setID(ID);
        createFields();
        updateBoxModelToConnection();
        fieldIdentifier.setText(ID);
    }

    public ConnectionGUI(Connection lConnection, MainController modelGuiController)
    {
        guiController = modelGuiController;
        activeConnection = lConnection;
        createFields();
        updateBoxModelToConnection();
        boxType.setSelectedItem(activeConnection.getType());
        if(activeConnection.getEndElement() != null)
        {
            endElementBox.setSelectedItem(activeConnection.getEndElement().toString());
        }
        fieldIdentifier.setText(activeConnection.getIdentifier());
        if (activeConnection.getBottomCenter() != null)
        {
            fieldBottomCenter.setText(activeConnection.getBottomCenter());
        }
        if (activeConnection.getMultiplicityEnd() != null)
        {
            fieldEndMulti.setText(activeConnection.getMultiplicityEnd());
        }
        if (activeConnection.getDescriptionEnd() != null)
        {
            fieldEndText.setText(activeConnection.getDescriptionEnd());
        }
        if (activeConnection.getLevel() > -1)
        {
            fieldLevel.setText(Integer.toString(activeConnection.getLevel()));
        }
        if (activeConnection.getMultiplicityStart() != null)
        {

            fieldStartMulti.setText(activeConnection.getMultiplicityStart());
        }
        if (activeConnection.getDescriptionStart() != null)
        {
            fieldStartText.setText(activeConnection.getDescriptionStart());
        }
        if (activeConnection.getTopCenter() != null)
        {
            fieldTopCenter.setText(activeConnection.getTopCenter());
        }
        if (activeConnection.getNotes() != null)
        {
            stringArrayEditor.setText(activeConnection.getNotes());
        }
    }

    private void createFields()
    {
        initComponents();
        for (String type : guiController.getAllowedConnections())
        {
            boxType.addItem(type);
        }
        for (Element element : guiController.getElements())
        {
            endElementBox.addItem(element.toString());
        }
        linkFileChooser.setFileFilter(guiController.getJSONfilter());
    }

    protected void updateBoxModelToConnection()
    {
        boxLinkedModelC.removeAllItems();
        for (String temp : activeConnection.getLinkedModels())
        {
            boxLinkedModelC.addItem(temp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        boxType = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        stringArrayEditor = new javax.swing.JEditorPane();
        jLabel12 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldIdentifier = new javax.swing.JTextField();
        fieldTopCenter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldBottomCenter = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldStartText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldStartMulti = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldEndText = new javax.swing.JTextField();
        fieldEndMulti = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        endElementBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        fieldLevel = new javax.swing.JTextField();
        boxLinkedModelC = new javax.swing.JComboBox<>();
        loadLinkedModelC = new javax.swing.JButton();
        linkModelToC = new javax.swing.JButton();
        unlinkModelFromC = new javax.swing.JButton();

        jLabel2.setText("Type:");

        boxType.setAlignmentX(0.0F);

        jScrollPane2.setViewportView(stringArrayEditor);

        jLabel12.setText("Notes: ");

        saveButton.setText("Save Connection");
        saveButton.setAlignmentX(0.5F);
        saveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Identifier:");

        fieldIdentifier.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldIdentifier.setAlignmentX(0.0F);
        fieldIdentifier.setEnabled(false);

        fieldTopCenter.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldTopCenter.setAlignmentX(0.0F);

        jLabel3.setText("Text top center:");

        jLabel4.setText("Text bottom center:");

        fieldBottomCenter.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldBottomCenter.setAlignmentX(0.0F);

        jLabel5.setText("Text start:");

        fieldStartText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldStartText.setAlignmentX(0.0F);

        jLabel6.setText("Multiplicity start:");

        fieldStartMulti.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldStartMulti.setAlignmentX(0.0F);

        jLabel7.setText("Text end:");

        jLabel8.setText("Multiplicity end:");

        fieldEndText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldEndText.setAlignmentX(0.0F);

        fieldEndMulti.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldEndMulti.setAlignmentX(0.0F);

        jLabel9.setText("End element:");

        endElementBox.setAlignmentX(0.0F);

        jLabel10.setText("Level:");

        fieldLevel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldLevel.setAlignmentX(0.0F);

        loadLinkedModelC.setText("Load linked model");
        loadLinkedModelC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loadLinkedModelCActionPerformed(evt);
            }
        });

        linkModelToC.setText("Add linked model");
        linkModelToC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                linkModelToCActionPerformed(evt);
            }
        });

        unlinkModelFromC.setText("Remove linked model");
        unlinkModelFromC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                unlinkModelFromCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldTopCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(fieldBottomCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(fieldStartText, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(fieldStartMulti, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(fieldEndText)
                                    .addComponent(fieldEndMulti)
                                    .addComponent(endElementBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxLinkedModelC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(loadLinkedModelC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(unlinkModelFromC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(linkModelToC, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(saveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(boxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldTopCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkModelToC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldBottomCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boxLinkedModelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldStartText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loadLinkedModelC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldStartMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unlinkModelFromC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(fieldEndText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldEndMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(endElementBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveButtonActionPerformed
    {//GEN-HEADEREND:event_saveButtonActionPerformed
        Object[] options =
        {
            "Yes, save",
            "No, don't save"
        };
        int n = JOptionPane.showOptionDialog(null, "Do you want to save your changes?", "Save changes?", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]);
        if (n == 0)
        {
            saveConnection();
            guiController.loadAllInstances();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadLinkedModelCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loadLinkedModelCActionPerformed
    {//GEN-HEADEREND:event_loadLinkedModelCActionPerformed
        if (boxLinkedModelC.getSelectedItem() != null)
        {
            saveConnection();
            guiController.saveChanges();
            guiController.loadLinkedModel(boxLinkedModelC.getSelectedItem().toString());
            guiController.closeConnection();
        }
    }//GEN-LAST:event_loadLinkedModelCActionPerformed

    private void unlinkModelFromCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_unlinkModelFromCActionPerformed
    {//GEN-HEADEREND:event_unlinkModelFromCActionPerformed
        String link = boxLinkedModelC.getSelectedItem().toString();
        {
            if (activeConnection.getLinkedModels().contains(link))
            {

                activeConnection.getLinkedModels().remove(link);
                updateBoxModelToConnection();
            }
        }
    }//GEN-LAST:event_unlinkModelFromCActionPerformed

    private void linkModelToCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_linkModelToCActionPerformed
    {//GEN-HEADEREND:event_linkModelToCActionPerformed

        // sets it to only accept files
        linkFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        //opens the file selection pane and sets the file path
        int returnValue = linkFileChooser.showOpenDialog(null);
        File linkedFile = null;

        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            linkedFile = linkFileChooser.getSelectedFile();
            String path = guiController.getRelativePath(linkedFile);
            activeConnection.getLinkedModels().add(path);
            updateBoxModelToConnection();
        }
    }//GEN-LAST:event_linkModelToCActionPerformed

    private void saveConnection()
    {
        if (startingElement != null)
        {

            saveCConnection();
            startingElement.addConnection(activeConnection);
        }
        else
        {
            saveCConnection();
        }
        System.out.println(activeConnection.getType() + " : " + activeConnection.getTopCenter());
    }

    private void saveCConnection()
    {
        activeConnection.setID(fieldIdentifier.getText());
        activeConnection.setType(boxType.getSelectedItem().toString());
        activeConnection.setBottomCenter(fieldBottomCenter.getText());
        activeConnection.setEndMultiplicity(fieldEndMulti.getText());
        activeConnection.setEndText(fieldEndText.getText());
        if (fieldLevel.getText().length() > 0 && fieldLevel.isEnabled())
        {
            try
            {
                int levelEntry = Integer.parseInt(fieldLevel.getText());
                if (levelEntry >= 0)
                {
                    activeConnection.setLevel(levelEntry);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Not a valid number, number needs to be 0 or higher.");
                    activeConnection.setLevel(-1);
                }
            }
            catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "Not a valid number entered.");
            }
        }
        else
        {
            activeConnection.setLevel(-1);
        }
        activeConnection.setStartMultiplicity(fieldStartMulti.getText());
        activeConnection.setStartText(fieldStartText.getText());
        activeConnection.setTopCenter(fieldTopCenter.getText());
        activeConnection.setNotes(stringArrayEditor.getText());
        String elementID = endElementBox.getSelectedItem().toString();
        int split = elementID.indexOf(" : ");
        elementID = elementID.substring(0, split);
        activeConnection.setEndElement(guiController.findElement(elementID));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxLinkedModelC;
    private javax.swing.JComboBox<String> boxType;
    private javax.swing.JComboBox<String> endElementBox;
    private javax.swing.JTextField fieldBottomCenter;
    private javax.swing.JTextField fieldEndMulti;
    private javax.swing.JTextField fieldEndText;
    private javax.swing.JTextField fieldIdentifier;
    private javax.swing.JTextField fieldLevel;
    private javax.swing.JTextField fieldStartMulti;
    private javax.swing.JTextField fieldStartText;
    private javax.swing.JTextField fieldTopCenter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton linkModelToC;
    private javax.swing.JButton loadLinkedModelC;
    private javax.swing.JButton saveButton;
    private javax.swing.JEditorPane stringArrayEditor;
    private javax.swing.JButton unlinkModelFromC;
    // End of variables declaration//GEN-END:variables

}
